[global]
type=global
endpoint_identifier_order=username,ip,anonymous
keep_alive_interval=30

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
local_net=192.168.0.0/24
external_signaling_address=192.168.0.161

[1001]
type=endpoint
transport=transport-udp
aors=1001
auth=auth1001
context=internal
disallow=all
allow=ulaw,alaw,gsm
direct_media=no
force_rport=yes
rtp_symmetric=yes
rewrite_contact=yes

[auth1001]
type=auth
auth_type=userpass
username=1001
password=Test1001!

[1001]
type=aor
max_contacts=5
remove_existing=yes

[1002]
type=endpoint
transport=transport-udp
aors=1002
auth=auth1002
context=internal
disallow=all
allow=ulaw,alaw,gsm
direct_media=no
force_rport=yes
rtp_symmetric=yes
rewrite_contact=yes

[auth1002]
type=auth
auth_type=userpass
username=1002
password=Test1002!

[1002]
type=aor
max_contacts=5
remove_existing=yes
