; ─── Trunk hacia voip-media-01 ───────────────────────────────
[transport-media]
type=transport
protocol=udp
bind=0.0.0.0:5061

[media-server]
type=endpoint
context=from-media
disallow=all
allow=ulaw
allow=alaw
allow=gsm
outbound_auth=auth-media
aors=media-server-aor
direct_media=no
rtp_symmetric=yes

[auth-media]
type=auth
auth_type=userpass
username=netvoice-lab
password=NetvoiceMedia2024

[media-server-aor]
type=aor
contact=sip:192.168.0.18:5060

[from-media]
type=identify
endpoint=media-server
match=192.168.0.18
