[settings]
ps_endpoints => mysql,general,ps_endpoints
ps_auths => mysql,general,ps_auths
ps_aors => mysql,general,ps_aors
ps_endpoint_id_ips => mysql,general,ps_endpoint_id_ips
ps_contacts => mysql,general,ps_contacts
