[general]
static=yes
writeprotect=no
clearglobalvars=no

[internal]
exten => _1XXX,1,NoOp(Llamada de ${CALLERID(num)} hacia ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN},30)
 same => n,Hangup()

[default]
exten => s,1,Hangup()
